# Generated by Django 5.1.5 on 2025-08-20 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_last_update_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت'), ('Processing', 'در حال پردازش'), ('Shipped', 'ارسال شده به پست'), ('Delivered', 'تحویل داده شده'), ('Cancelled', 'سفارش لغو شده'), ('Failed', 'پرداخت ناموفق')], default='Pending', max_length=50),
        ),
    ]
