# Generated by Django 5.1.5 on 2025-08-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_uuid_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='mount_paid',
            new_name='amount_paid',
        ),
    ]
