# Generated by Django 5.1.3 on 2024-11-25 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_is_sale_product_slae_price_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 25, 12, 13, 58, 901448)),
        ),
    ]
