# Generated by Django 5.1.3 on 2024-11-25 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slae_price',
            new_name='sale_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 25, 12, 20, 41, 771474)),
        ),
    ]
