# Generated by Django 5.1.3 on 2024-12-10 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_order_date_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 10, 19, 44, 51, 986851)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
