# Generated by Django 5.1.3 on 2024-12-10 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_order_date_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 10, 20, 1, 51, 156168)),
        ),
    ]
