# Generated by Django 5.1.3 on 2024-12-12 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_order_date_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address2',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 12, 19, 3, 12, 208465)),
        ),
    ]
