# Generated by Django 5.1.3 on 2024-12-31 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_alter_order_date_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 31, 9, 59, 24, 711447)),
        ),
    ]
