# Generated by Django 5.1.3 on 2024-12-31 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 31, 10, 33, 3, 57285)),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
