# Generated by Django 5.1.3 on 2024-12-31 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_remove_order_payment_alter_order_date_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 31, 17, 4, 40, 583547)),
        ),
    ]
