# Generated by Django 5.1.5 on 2025-01-23 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_rename_phone_number_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 23, 14, 31, 14, 465413)),
        ),
    ]
