# Generated by Django 5.1.5 on 2025-05-08 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 8, 14, 24, 16, 94399)),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
