# Generated by Django 5.1.5 on 2025-08-09 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0075_remove_order_customer_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 8, 9, 14, 19, 15, 10722)),
        ),
    ]
