# Generated by Django 5.1.5 on 2025-08-09 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 8, 9, 17, 57, 11, 931323)),
        ),
    ]
