# Generated by Django 5.1.5 on 2025-08-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0079_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.CharField(max_length=500),
        ),
    ]
